version: "3.8"

services:
  frontend:
    build:
      context: . # Use the current directory
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=production
